{{- /*
* Eclipse Tractus-X - Industry Core Hub
*
* Copyright (c) 2025 Contributors to the Eclipse Foundation
*
* See the NOTICE file(s) distributed with this work for additional
* information regarding copyright ownership.
*
* This program and the accompanying materials are made available under the
* terms of the Apache License, Version 2.0 which is available at
* https://www.apache.org/licenses/LICENSE-2.0.
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
* WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
* License for the specific language governing permissions and limitations
* under the License.
*
* SPDX-License-Identifier: Apache-2.0
*/}}

{{- if .Values.backend.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  labels:
    {{- include "industry-core-hub.backend.labels" . | nindent 4 }}
data:
  configuration.yml: |-
    hostname: {{ include "industry-core-hub.ingressUrl" . | quote }}
    authorization:
      enabled: {{ .Values.backend.configuration.authorization.enabled }}
      apiKey: 
        key: {{ .Values.backend.configuration.authorization.apiKey.key | quote }}
        value: {{ .Values.backend.configuration.authorization.apiKey.value | quote }}
    agreements: {{ .Values.backend.configuration.agreements | toYaml | nindent 6 }}
    database:
      connectionString: {{ include "industry-core-hub.postgresql.dsn" . | quote }}
      echo: {{ .Values.backend.configuration.database.echo }}
    cors: {{ .Values.backend.cors | toYaml | nindent 6 }}
    consumer: {{ .Values.backend.configuration.consumer | toYaml | nindent 6 }}
    provider: {{ .Values.backend.configuration.provider | toYaml | nindent 6 }}
    submodel_dispatcher: {{ .Values.backend.configuration.submodel_dispatcher | toYaml | nindent 6 }}
  logging.yml: |-
    version: 1
    disable_existing_loggers: False

    formatters:
      default:
        format: '%(asctime)s [%(levelname)-8s] [%(name)-15s] %(message)s'
        datefmt: '%Y-%m-%d %H:%M:%S'

    handlers:
      console:
        class: logging.StreamHandler
        formatter: default
        level: DEBUG
        stream: ext://sys.stdout
      file:
        class: logging.handlers.RotatingFileHandler
        formatter: default
        mode: a

    loggers:
      development:
        level: DEBUG
        handlers: [console, file]
        propagate: no

      staging:
        level: INFO
        handlers: [console, file]
        propagate: no

      production:
        level: WARNING
        handlers: [file]
        propagate: no

    root:
      level: {{ .Values.backend.configuration.logger.level | quote }}
      handlers: [console, file]
{{- end -}}