#################################################################################
# Eclipse Tractus-X - Industry Core Hub Backend
#
# Copyright (c) 2025 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License, Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
# either express or implied. See the
# License for the specific language govern in permissions and limitations
# under the License.
#
# SPDX-License-Identifier: Apache-2.0
#################################################################################

participantId: "BPNL00000003CRHK"
hostname: "https://ichub-backend.url"
authorization:
  enabled: true
  apiKey: 
    key: "X-Api-Key"
    value: <<example>>
agreements:
  - semanticid: urn:samm:io.catenax.part_type_information:1.0.0#PartTypeInformation
    usage:
      context:
        odrl: http://www.w3.org/ns/odrl/2/
        cx-policy: https://w3id.org/catenax/policy/
      permission:
        - action: odrl:use
          LogicalConstraint: odrl:and
          constraints:
            - leftOperand: cx-policy:FrameworkAgreement
              operator: odrl:eq
              rightOperand: DataExchangeGovernance:1.0
            - leftOperand: cx-policy:Membership
              operator: odrl:eq
              rightOperand: active
            - leftOperand: cx-policy:UsagePurpose
              operator: odrl:eq
              rightOperand: cx.core.industrycore:1
      prohibition: []
      obligation: []
    access:
      context:
        odrl: http://www.w3.org/ns/odrl/2/
        cx-policy: https://w3id.org/catenax/policy/
      permission:
        - action: odrl:use
          constraints:
            - leftOperand: cx-policy:Membership
              operator: odrl:eq
              rightOperand: active
      prohibition: []
      obligation: []
database:
  connectionString: "postgresql://user:password@localhost:5432/ichub"
  echo: false
edc:
  controlplane:
    hostname: https://edc-consumer-ichub-control.int.catena-x.net
    apikeyheader: X-Api-Key
    apikey: ACA176440A8BDD3954FCEC3552BF8985AFB75608A57B9121EA809791854AAA2BEDBF85333572E8DECE9537D69697D6BA28EA26174085242CB536B7877E219CAC
    managementpath: /management
    protocolPath: /api/v1/dsp
    catalogPath: /catalog
  dataplane:
    hostname: https://edc-provider-ichub-dataplane.int.catena-x.net
    publicPath: "/api/public"
digitalTwinRegistry:
  hostname: https://dtr-ichub.int.catena-x.net
  apiPath: /api/v3
  uri: ""
  asset_config:
    dct_type: "https://w3id.org/catenax/taxonomy#DigitalTwinRegistry"
    # existing_asset_id: <registry-asset> # -- In case an existing DTR asset wants to be used specify here the id, otherwise it will be created based on the url, if it not exists it will be created
  lookup:
    uri: ""
  policy:
    usage:
      context:
        odrl: http://www.w3.org/ns/odrl/2/
        cx-policy: https://w3id.org/catenax/policy/
      permission:
        - action: odrl:use
          LogicalConstraint: odrl:and
          constraints:
            - leftOperand: cx-policy:FrameworkAgreement
              operator: odrl:eq
              rightOperand: DataExchangeGovernance:1.0
            - leftOperand: cx-policy:Membership
              operator: odrl:eq
              rightOperand: active
            - leftOperand: cx-policy:UsagePurpose
              operator: odrl:eq
              rightOperand: cx.core.digitalTwinRegistry:1
      prohibition: []
      obligation: []
    access:
      context:
        odrl: http://www.w3.org/ns/odrl/2/
        cx-policy: https://w3id.org/catenax/policy/
      permission:
        - action: odrl:use
          constraints:
            - leftOperand: cx-policy:Membership
              operator: odrl:eq
              rightOperand: active
      prohibition: []
      obligation: []

submodel_dispatcher:
  path: "./data/submodels"
  apiPath: /submodel-dispatcher