###############################################################
# Eclipse Tractus-X - Industry Core Hub
#
# Copyright (c) 2025 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License, Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
# SPDX-License-Identifier: Apache-2.0
###############################################################
---
## For being used in the Integration ArgoCD test environment from the Catena-X Association

postgresql:
  auth:
    ## Root password override
    password: <path:industry-core-hub/data/db#rootPass>
    ## Industry Core User Password
    ichubPassword: <path:industry-core-hub/data/db#ichubPass>
  ingress:
    enabled: true
    ingressClassName: "nginx"
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
      - host: metadata-registry.int.catena-x.net
        paths:
          - path: /
            pathType: Prefix
    tls:
       - secretName: "metadata-registry.int.catena-x.net-tls"
         hosts:
           - "metadata-registry.int.catena-x.net" 
    
# -- pgAdmin4 configuration
pgadmin4:
  enabled: true
  env:
    email: <path:industry-core-hub/data/pgadmin#email>
    password: <path:industry-core-hub/data/pgadmin#password>
  ingress:
    enabled: true
    ingressClassName: "nginx"
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
      - host: pgadmin-ichub.int.catena-x.net
        paths:
          - path: /
            pathType: Prefix
    tls:
       - secretName: "pgadmin-ichub.int.catena-x.net-tls"
         hosts:
           - "pgadmin-ichub.int.catena-x.net" 
