name: "Eclipse DASH IP Check"

on:
  push:
    branches: [main, feat/add-Dash-License]
    paths:
      - '**.txt'
  pull_request:
    branches: [main]
    paths:
      - '**.txt'
  workflow_dispatch:

jobs:
  check-dependencies-backend:
    runs-on: ubuntu-latest
    steps:

      - name: Set up JDK 17
        uses: actions/setup-java@3a4f6e1af504cf6a31855fa899c6aa5355ba6c12 # v4.7.0
        with:
          distribution: 'temurin'
          java-version: '21'
    
      - name: Set up Python
        uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38 # v5.4.0
        with:
            python-version: '3.10'

      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Install dependencies
        run: pip install -r ichub-backend/requirements.txt

      - name: List packages
        run: |
            pip list --format=freeze | grep -Pv "^(pip|setuptools|wheel|virtualenv|distlib|pkg_resources)" | awk -F'==' '{print "pypi/pypi/-/" $1 "/" $2}' | awk '!seen[$0]++' > PACKAGE


      - name: Generate Dependencies file
        run: |
            curl -L --output ./org.eclipse.dash.licenses-1.1.1.jar 'https://repo.eclipse.org/service/local/artifact/maven/redirect?r=dash-licenses&g=org.eclipse.dash&a=org.eclipse.dash.licenses&v=LATEST'
            java -jar ./org.eclipse.dash.licenses-1.1.1.jar PACKAGES -project automotive.tractusx -summary DEPENDENCIES_IC-BACKEND || true

      - name: Check if dependencies were changed
        id: dependencies-changed
        run: |
            if git diff --exit-code DEPENDENCIES_IC-BACKEND; then
                echo "changed=false" >> $GITHUB_OUTPUT
            else
                echo "changed=true" >> $GITHUB_OUTPUT
            fi

      - name: Check for restricted dependencies
        run: |
            restricted=$(grep 'restricted' DEPENDENCIES_IC-BACKEND || true)
            if [[ -n "$restricted" ]]; then
                echo "The following dependencies are restricted: $restricted"
                exit 1
            fi
        if: steps.dependencies-changed.outputs.changed == 'true'

      - name: Upload DEPENDENCIES_IC-BACKEND file
        uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08 # v4.6.0
        with:
            path: DEPENDENCIES
        if: steps.dependencies-changed.outputs.changed == 'true'

