name: Lint and Test Charts

on:
    push:
      paths:
        - 'charts/industry-core-hub/**'
        - '.github/workflows/helm-test.yaml'
      branches: main
    pull_request:
      paths:
        - 'charts/industry-core-hub/**'
        - '.github/workflows/helm-test.yaml'
    workflow_dispatch:
      inputs:
        node_image:
          description: 'kindest/node image for k8s kind cluster'
          # k8s version from 3.1 release as default
          default: 'kindest/node:v1.27.3'
          required: false
          type: string
        upgrade_from:
          description: 'chart version to upgrade from'
          # chart version from 3.1 release as default
          default: 'x.x.x'
          required: false
          type: string
        helm_version:
          description: 'helm version to test (default = latest)'
          default: 'latest'
          required: false
          type: string

jobs:
    lint-test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                fetch-depth: 0

            - name: Kubernetes KinD Cluster
              uses: container-tools/kind-action@v1
              with:
                # upgrade version, default (v0.17.0) uses node image v1.21.1 and doesn't work with more recent node image versions
                version: v0.20.0
                # default value for event_name != workflow_dispatch
                node_image: ${{ github.event.inputs.node_image || 'kindest/node:v1.27.3' }}

            - name: Build backend image
              uses: docker/build-push-action@v3
              with:
                context: "{{defaultContext}}:ichub-backend"
                push: true
                tags: kind-registry:5000/ichub-backend:latest

            #- name: Build frontend image
            #  uses: docker/build-push-action@v3
            #  with:
            #    context: "{{defaultContext}}:ichub-frontend"
            #    push: true
            #    tags: kind-registry:5000/ichub-frontend:latest

            - name: Set up Helm
              uses: azure/setup-helm@v3
              with:
                version: ${{ github.event.inputs.helm_version || 'latest' }}

            - uses: actions/setup-python@v4
              with:
                python-version: '3.9'
                check-latest: true
            - name: Set up chart-testing
              uses: helm/chart-testing-action@v2.3.1

            - name: Run chart-testing (list-changed)
              id: list-changed
              run: |
                changed=$(ct list-changed --target-branch ${{ github.event.repository.default_branch }})
                if [[ -n "$changed" ]]; then
                  echo "changed=true" >> $GITHUB_OUTPUT
                fi

            - name: Run chart-testing (lint)
              run: ct lint --validate-maintainers=false --target-branch ${{ github.event.repository.default_branch }}
            - name: Run chart-testing (install)
              run: ct install --charts charts/industry-core-hub
              if: github.event_name != 'pull_request' || steps.list-changed.outputs.changed == 'true'

              # Upgrade the released chart version with the locally available chart
              # default value for event_name != workflow_dispatch
            - name: Run helm upgrade
              run: |
                helm repo add bitnami https://charts.bitnami.com/bitnami
                helm repo add tractusx-dev https://eclipse-tractusx.github.io/charts/dev
                helm install [NAME] tractusx-dev/[CHART] --version ${{ github.event.inputs.upgrade_from || 'x.x.x' }}
                helm dependency update charts/[CHART]
                helm upgrade [NAME] charts/[CHART]
              if: github.event_name != 'pull_request' || steps.list-changed.outputs.changed == 'true'